version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
      #- "8081:8081"
    depends_on:
      - db
    stop_signal: SIGINT
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=TP_BDD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 15
volumes:
  pgdata: